version: '3.9'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Map port 3000 on the host to the container
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3080:3080" # Map port 3080 on the host to the container
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules